### ISSUE TITLE
release version 1.4.0

### ISSUE THREAD

**Issue by jgmbenoit** [IMAGINARY/jsurf#4]
Please provide a Release for the latest version 1.4.0 .
Note also that some jsurf scripts in examples have the executable privilege:
it would be great to remove their executable privilege before the release.

**Comment by porst17** [comment]
You mean a release on github? AKA https://github.com/IMAGINARY/jsurf/releases?

**Comment by jgmbenoit** [comment]
Indeed, I meant a release on github in such that a source tar bar is available for the rest of the world.

**Comment by porst17** [comment]
BTW the version is still 0.1.4 i.e. the API is still very likely to change in future versions (once I have time to work on jsurf again)

**Comment by porst17** [comment]
I will do the release on Monday. I want to add a CHANGELOG for all older versions as well.

**Comment by jgmbenoit** [comment]
As it appeared that its Java dependencies are packaged, I am on my way to package it in the Debian way (read without gradle).  So far, the package build well on Jessie and Sid with the default Java (not Oracle one).

Questions:
1] I plan to call the package jsurf-alggeo, is it fine ?
2] there are a couple of `public static void main' in the `src/main', which one is the good one ?

**Comment by jgmbenoit** [comment]
is de.mfo.jsurf.grid.RotationGrid.main working ?

**Comment by porst17** [comment]
I released all old versions as well as v0.1.4 (proper git tags and source zip / tar balls on github).

jsurf is mainly intended to be used as a library, but it has a minimal command line interface for convenience though. Here's the [main class](https://github.com/IMAGINARY/jsurf/tree/master/src/main/java/de/mfo/jsurf/Main.java).
