### ISSUE TITLE
Default to headless operation

### ISSUE THREAD

**Issue by porst17** [IMAGINARY/jsurf#6]
So far, jsurf shows a window to display the rendered surface if no `--output` parameter is given. A more sane default would be to use `--output jsurf_filename.png` and only open a GUI if `--gui` is given.

**Comment by porst17** [comment]
@jgmbenoit: I hope the new cli interface is sound
```
﻿﻿usage: jsurf [options] jsurf_input png_output

jsurf is a renderer for real algebraic surfaces.
Specify files as '-' for standard input and output.
    --gui             display the rendering (png_output becomes optional)
    --help            display this help text and exit
 -q,--quality <arg>   quality of the rendering: 0 (low), 1 (medium,
                      default), 2 (high), 3 (extreme)
 -s,--size <arg>      image width and height (default: 100)
    --version         print program version and exit
```

**Comment by jgmbenoit** [comment]
By headless, I really meant headless: is a GUI really needed here ?
I think that this library may be kept script oriented, and burn energy about it along this direction.
Being headless meant that it can be install on headless boxes which are aimed to crunch numbers (for example). There is a lot of ready to use image viewers around: we can hardly compete with them here, so just wipe out this candy feature. Having the possibility to deal with other image formats will be more useful here, in particular with vector format.

**Comment by porst17** [comment]
Not all users prefer Linux and command line. The gui is a requested feature. Its rather basic, but a nice convenience feature.

You can install the library on a headless machine. No problem. In Java, this is detected during runtime. I can disable the `--gui` option on headless machines, if you want. And I don't mind if you package `jsurf` without dependency on a display server.

This issues is about headless operation. If you want new features like new image formats, open a new issue.

Anyway, supporting additional image formats is unnecessary. The PNG stores all information generated by jsurf in a lossless manner. There are a lot of ready to use image converters around: we can hardly compete with them here.

Even if I add this candy feature, there will probably never be support for a vector format. `jsurf` performs the rendering via ray tracing to achieve it's high image quality. Ray tracing produces raster images by definition. The best I could do would be to wrap the raster image into some vector format container, which does not make any sense. Vector format support would make sense if `jsurf` would compute some kind of triangle mesh for the surface. But high quality mesh generation is incredibly hard for algebraic surfaces. Even though the algorithms for this task are extremely sophisticated and orders of magnitude slower than ray tracing, the visual results are usually much worse, since the mesh has to be very dense to provide a similar look. There are some efficient algorithms for simple non-singular algebraic surfaces, though, but *simple* surfaces are not why `jsurf` has been created in the first place.

If you want to continue the discussion about additional image formats, please open a new issue.

**Comment by porst17** [comment]
The `--gui` option is disabled in headless mode as of a0693f4.

**Comment by jgmbenoit** [comment]
"There are a lot of ready to use image converters around: we can hardly compete with them here."
Ok.
The same argument can be hold for image viewers, hence my suggestion to drop it out.

**Comment by jgmbenoit** [comment]
Second, I guess that jsurfer may provide the GUI for jsurf.

**Comment by porst17** [comment]
To end the discussion: The minimal gui will stay. Your argument about jsurfer is valid. But the minimal gui is just about 15 lines of code altogether, compared to the > 5000 LOCs of jsurfer. This is negligible and the code is straight forward to maintain. It's just there for convenience, also for me as a developer. It's disabled in headless setups and therefore should not cause any problems in your setup.
