### ISSUE TITLE
[wishlist] quid reproducible comment inside the PNG metadata ?

### ISSUE THREAD

**Issue by jgmbenoit** [IMAGINARY/jsurf#7]
Just a suggestion add some comment to each generated PNG, a reproducible comment [1]. Example:

Created by jsurf version MAJOR \<http://www.imaginary.org/>
Copyright: <IMAGE COPYRIGHT>
Quality: 3

[1] https://wiki.debian.org/ReproducibleBuilds

**Comment by porst17** [comment]
The PNG standard defines the following meta data keywords:

Title 	Short (one line) title or caption for image
- Author: Name of image's creator
- Description: Description of image (possibly long)
- Copyright: Copyright notice
- Creation Time: Time of original image creation
- Software: Software used to create the image
- Disclaimer: Legal disclaimer
- Warning: Warning of nature of content
- Source: Device used to create the image
- Comment: Miscellaneous comment

In my opinion, the only meta data that makes sense is `Software`, i.e. I could imaging using
```
Software: jsurf version MAJOR.MINOR.PATCH (http://imaginary.org/program/jsurf)
Creation Time: yyyy-mm-dd HH:MM:ss
```

Is this what you thought of?

**Comment by jgmbenoit** [comment]
Recording the software name and its version at creation time is definitely a good idea.
The `Creation Time' can be an issue when reproducibility is an issue --- and it may contained the time zone (Zulu zone is a good default: -> ISO 8601 [1] )
I had essentially in mind to record the jsurf parameters effectively used to create the image: I guess that this information may be set in the `Comment' metadata, or may be in the `Source' in such a way that the final creator can put it own comments. The idea is to give enough information (beside the PNG ones) to allow the re-creation of the image: Quality is a parameter specific to jsurf (and it is hard to guessed), as such it may be recorded.

[1] https://en.wikipedia.org/wiki/ISO_8601

**Comment by porst17** [comment]
In order to support reproducible builds, `CreationTime` will use `SOURCE_DATE_EPOCH` if it is defined in the environment as suggested on https://wiki.debian.org/ReproducibleBuilds/Howto.

**Comment by porst17** [comment]
I also use ISO 8601 to format the `CreationDate`. Thanks for pointing me to that.
